[package]
name = "noxis-private-proof-contract"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
noxis-nullifier-tree-reference = { path = "../noxis-nullifier-tree-reference" }
noxis-nullifier-tree-state = { path = "../noxis-nullifier-tree-state" }
noxis-poseidon2-reference = { path = "../noxis-poseidon2-reference" }
noxis-poseidon2-privacy-reference = { path = "../noxis-poseidon2-privacy-reference" }
noxis-stark-experiment = { path = "../noxis-stark-experiment" }
noxis-private-state = { path = "../noxis-private-state" }
noxis-storage = { path = "../noxis-storage" }
noxis-private-packet-validation = { path = "../noxis-private-packet-validation" }
noxis-privacy-types = { path = "../noxis-privacy-types" }
noxis-types = { path = "../noxis-types" }
noxis-tree-params = { path = "../noxis-tree-params" }
sha2 = "0.10.9"

[dev-dependencies]
noxis-codec = { path = "../noxis-codec" }
noxis-wallet-crypto = { path = "../noxis-wallet-crypto" }

[lints]
workspace = true
