[package]
name = "noxis-poseidon2-privacy-reference"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
noxis-poseidon2-reference = { path = "../noxis-poseidon2-reference" }
noxis-tree-params = { path = "../noxis-tree-params" }

[dev-dependencies]
sha2 = "0.10.9"

[lints]
workspace = true
